# Generated by Django 3.1.2 on 2022-10-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20220626_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_token',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
