# Generated by Django 4.1 on 2023-04-25 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
      ("articles", "0005_auto_20230331_2055"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
