# Generated by Django 3.1.2 on 2022-12-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20221222_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('that_comment_id', models.IntegerField(default=0)),
                ('replies_number', models.IntegerField(default=0)),
            ],
        ),
    ]
