# Generated by Django 3.1.2 on 2022-12-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_commentreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='replies_number',
            field=models.IntegerField(default=0),
        ),
    ]
