# Generated by Django 4.1.7 on 2023-03-30 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_comment_replies_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentReply',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='replies_number',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='that_comment_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.comment'),
        ),
    ]
