# Generated by Django 3.1.2 on 2023-06-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20230428_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='topic',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
