# Generated by Django 4.1.7 on 2023-08-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_article_likes_comment_token_alter_article_categorie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='token',
            field=models.CharField(max_length=500),
        ),
    ]
