# Generated by Django 3.1.2 on 2022-06-26 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0001_initial'),
        ('cours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videolesson',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning.categorie'),
        ),
    ]
