# Generated by Django 3.1.2 on 2022-10-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0002_videolesson_categorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('content', models.TextField(blank=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
